# -*- coding: utf-8 -*-
"""FashionVisionNet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tJrYi9iw6NclT7OGkpCo-V9ir3DKz_fu
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical

""" **Step 1: Load the CSV Files**"""

train_df = pd.read_csv('/content/fashion-mnist_train.csv')
test_df = pd.read_csv('/content/fashion-mnist_test.csv')

x_train = train_df.iloc[:, 1:].values  # All columns except the first one
y_train = train_df.iloc[:, 0].values   # The first column is the label

x_test = test_df.iloc[:, 1:].values
y_test = test_df.iloc[:, 0].values

# Normalize pixel values to range [0, 1]
x_train = x_train / 255.0
x_test = x_test / 255.0

# Reshape for CNN input and convert labels to one-hot encoding
x_train = x_train.reshape(-1, 28, 28, 1)
x_test = x_test.reshape(-1, 28, 28, 1)

y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)

print(f"x_train shape: {x_train.shape}, y_train shape: {y_train.shape}")
print(f"x_test shape: {x_test.shape}, y_test shape: {y_test.shape}")

"""**Step 2: Visualize the Data**"""

class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
               'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

plt.figure(figsize=(10, 10))
for i in range(9):
    plt.subplot(3, 3, i + 1)
    plt.imshow(x_train[i].reshape(28, 28), cmap='gray')
    plt.title(class_names[np.argmax(y_train[i])])
    plt.axis('off')
plt.show()

"""**Step 3: Build the CNN Model**"""

from tensorflow.keras import models, layers

# Define CNN model
model = models.Sequential([
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(128, (3, 3), activation='relu'),
    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(10, activation='softmax')
])

model.summary()

"""**Step 4: Compile the Model**"""

model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

"""**Step 5: Train the Model**"""

history = model.fit(
    x_train, y_train,
    epochs=15,
    validation_split=0.2,
    batch_size=64
)

"""**Step 6: Evaluate the Model**"""

test_loss, test_acc = model.evaluate(x_test, y_test, verbose=2)
print(f"Test accuracy: {test_acc:.4f}")

"""**Step 7: Visualize Predictions**"""

import numpy as np
import matplotlib.pyplot as plt

# Class names for Fashion-MNIST
class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
               'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

# Get predictions for the test set
predictions = model.predict(x_test)

# Function to plot images, predictions, and true labels
def plot_predictions(images, predictions, true_labels, num_images=9):
    plt.figure(figsize=(10, 10))
    for i in range(num_images):
        plt.subplot(3, 3, i + 1)
        plt.imshow(images[i].reshape(28, 28), cmap='gray')
        pred_label = np.argmax(predictions[i])
        true_label = np.argmax(true_labels[i])
        color = 'green' if pred_label == true_label else 'red'
        plt.title(f"Pred: {class_names[pred_label]}\nTrue: {class_names[true_label]}", color=color)
        plt.axis('off')
    plt.tight_layout()
    plt.show()

# Call the function
plot_predictions(x_test, predictions, y_test, num_images=9)

"""**Step 8: Save and Predict**"""

# Save the model
model.save("fashion_mnist_model.h5")

# Load and make predictions
loaded_model = models.load_model("fashion_mnist_model.h5")
predictions = loaded_model.predict(x_test[:5])

for i, pred in enumerate(predictions):
    print(f"Image {i+1}: Predicted - {class_names[np.argmax(pred)]}, Actual - {class_names[np.argmax(y_test[i])]}")

"""**1. Confusion Matrix**"""

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

# Get predicted class labels
y_pred = np.argmax(predictions, axis=1)
y_true = np.argmax(y_test, axis=1)

# Generate confusion matrix
cm = confusion_matrix(y_true, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=class_names)

# Plot confusion matrix
plt.figure(figsize=(10, 10))
disp.plot(cmap=plt.cm.Blues, values_format='d')
plt.title("Confusion Matrix")
plt.show()

"""**2. Classification Report**"""

from sklearn.metrics import classification_report

# Classification report
report = classification_report(y_true, y_pred, target_names=class_names)
print("Classification Report:\n")
print(report)

"""**3. Learning Curves**"""

# Plot training and validation accuracy and loss
plt.figure(figsize=(12, 5))

# Accuracy plot
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Accuracy over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

# Loss plot
plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Loss over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.tight_layout()
plt.show()

